//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHARP_Opdracht_WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel_Order
    {
        public int ArtikelID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Artikels Artikels { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
